services:
  scrutiny:
    image: ghcr.io/analogj/scrutiny:latest-omnibus
    container_name: scrutiny
    env_file:
      - .env
    cap_add:
      - SYS_RAWIO
    ports:
      - 127.0.0.1:8088:8080
      - 127.0.0.1:8089:8086
    volumes:
      - /run/udev:/run/udev:ro
      - ./config:/opt/scrutiny/config
      - ./influxdb:/opt/scrutiny/influxdb
    devices:
      - /dev:/dev
    restart: unless-stopped
