services:
  vikunja:
    image: vikunja/vikunja:latest
    container_name: vikunja
    env_file:
      - .env
    depends_on:
      - vikunja_db
      - vikunja_redis
    ports:
      - 127.0.0.1:3456:3456
    volumes:
      - ./files:/app/vikunja/files
    restart: unless-stopped

  vikunja_db:
    image: mariadb:11
    container_name: vikunja_db
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${VIKUNJA_DB_NAME}
      MYSQL_USER: ${VIKUNJA_DB_USER}
      MYSQL_PASSWORD: ${VIKUNJA_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${VIKUNJA_DB_ROOT_PASSWORD}
    volumes:
      - ./mariadb:/var/lib/mysql
    restart: unless-stopped

  vikunja_redis:
    image: redis:7-alpine
    container_name: vikunja_redis
    restart: unless-stopped
